hub:
  ros__parameters:
    noise_dist_std: 0.0   # 0.02 # this is multiplied by the range
    timestep: 0.1

main:
  ros__parameters:
    altitude: 5.0
    environment: "test"
    data_folder: "data"
    max_iteration: 30      # 30
    setting: "setting1"
    noise_time_std: 0.0   # 0.03 
    run: "run1"           # overwritten if launched from bash multiple times
    timestep: 0.1

test:
  ros__parameters:
    noise_dyna_std: 0.0   # 0.01 
    timestep: 0.05

#################################
#     OLD NOISE SETTINGS TESTED:    # 
#################################

# setting1:
# noise_dist_std: 0.0
# noise_time_std: 0.0
# noise_dyna_std: 0.0

# setting2:
# noise_dist_std: 0.05
# noise_time_std: 0.0
# noise_dyna_std: 0.0

# setting3:
# noise_dist_std: 0.0
# noise_time_std: 0.0
# noise_dyna_std: 0.01

# setting4:
# noise_dist_std: 0.0
# noise_time_std: 0.03
# noise_dyna_std: 0.0

# setting5:
# noise_dist_std: 0.05
# noise_time_std: 0.03
# noise_dyna_std: 0.01



#################################
#    NEW NOISE SETTINGS TESTED:    # 
#################################

# setting1:
# noise_dist_std: 0.0
# noise_time_std: 0.0
# noise_dyna_std: 0.0

# setting2:
# noise_dist_std: 0.05
# noise_time_std: 0.0
# noise_dyna_std: 0.0


# to relaunch
# setting3:
# noise_dist_std: 0.0
# noise_time_std: 0.0
# noise_dyna_std: 0.001

# setting4:
# noise_dist_std: 0.0
# noise_time_std: 0.2
# noise_dyna_std: 0.0

# setting5:
# noise_dist_std: 0.05
# noise_time_std: 0.2
# noise_dyna_std: 0.001