hub:
  ros__parameters:
    noise_dist_std: 0.0

main:
  ros__parameters:
    altitude: 5.0
    environment: "test"
    data_folder: "data"
    max_iteration: 5
    noise_dist_std: 0.2
    noise_time_std: 0.0
    run: 'run3'



## From main
# TIMESTEP = 0.1
# CHECK_UPDATE_TIME = 5
# ANCHOR_MOV_TIME = 1.0  # 1 s

# SWARM_COEF  = np.array([0.0, 1.0, 0.0])
# ANCHOR_COEF = np.vstack([-np.eye(3), np.eye(3)])



# SWARM_VEL = 0.2  # [m/s]
# ANCHOR_VEL = 1.0

## From Hub.py
# TIMESTEP = 0.02


## From test.py
# TIMESTEP = 0.02 # to put in the config file # 10 ms are enough